services:
  - type: web
    name: video-converter
    env: node
    plan: free
    buildCommand: "npm install && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /opt/render/project/src/yt-dlp && chmod a+rx /opt/render/project/src/yt-dlp"
    startCommand: "node server.js"
    envVars:
      - key: PATH
        value: /opt/render/project/src:$PATH
